# ==============================================================================
# Cyber-Tactical-Mint - Kitty Configuration
# ==============================================================================

# Fuente
font_family      Monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Ventana y Opacidad (Efecto HUD)
background_opacity         0.85
dynamic_background_opacity yes
window_padding_width       12

# Paleta de Colores Tácticos (Verde Fósforo / Militar)
foreground       #00FF41
background       #0a0f0d
selection_foreground #0a0f0d
selection_background #00FF41

# Colores de la terminal
color0  #1c2520
color8  #4d5d53
color1  #ff4141
color9  #ff5c5c
color2  #00FF41
color10 #33ff67
color3  #ffb800
color11 #ffd15c
color4  #00a3ff
color12 #5cbfff
color5  #d600ff
color13 #e55cff
color6  #00ffd1
color14 #5cffee
color7  #a1b5a9
color15 #ffffff

# Barra de pestañas
tab_bar_edge          top
tab_bar_style         powerline
active_tab_foreground #0a0f0d
active_tab_background #00FF41
inactive_tab_foreground #a1b5a9
inactive_tab_background #1c2520

# Configuración del cursor
cursor           #00FF41
cursor_shape     underline
cursor_blink_interval 0.5
