# ==============================================================================
# CONFIGURACIÓN: Terminal Táctica Kitty
# ==============================================================================

# Fuentes (Usa la tipografía que acabamos de descargar)
font_family      SpaceMono Nerd Font
bold_font        SpaceMono Nerd Font Bold
italic_font      SpaceMono Nerd Font Italic
font_size        11.0

# Ventana y Estética
background_opacity 0.85
dynamic_background_opacity yes
window_padding_width 12
hide_window_decorations yes

# Paleta de Colores (Cyberpunk / Terminal Militar)
foreground       #00FF66
background       #0a0f0d
selection_foreground #0a0f0d
selection_background #00FF66

# Los 16 colores de la terminal
color0  #101512
color8  #49514c
color1  #ff0055
color9  #ff3377
color2  #00ff66
color10 #33ff88
color3  #ffb700
color11 #ffcc33
color4  #00ffff
color12 #33ffff
color5  #9d00ff
color13 #b852ff
color6  #00a8ff
color14 #33bfff
color7  #e4e9e6
color15 #ffffff
